PLAYER_WIDTH = 400
PLAYER_HEIGHT = 300
PLAYER_VOLUME = 75
PLAYER_AUTOPLAY = False
PLAYER_LOOP = False
PLAYER_MUTE = False
PLAYER_THUMBNAILS = False
PLAYER_EMBED_CODE = True

VIDEO_DIR = "video/%Y/%m/%d/"
TEMP_VIDEO_DIR = "video"

ENCODING_AFREQ = 22050
ENCODING_ABITRATE = 64
ENCODING_FRAMERATE = 24
ENCODING_VBITRATE = 500
ENCODING_WIDTH = 320
ENCODING_HEIGHT = 240
ENCODING_LOG_FILE = "encoder.log"

THUMBNAIL_TIMESTEP = 60
THUMBNAIL_WIDTH = None
THUMBNAIL_MINIMUM_NUMBER = 3
THUMBNAIL_LOG_FILE = "thumbnailer.log"
THUMBNAIL_DIR = "thumbnails"

import sys

LOG_FUNCTION = lambda x: sys.stdout.write("%s\n" % x)
STOP_ON_ERRORS = True
